"""One-off: seed master.json from a Coda NZF_Master CSV export.

Usage (from repo root):
    python -m scripts.seed_master path/to/coda_master_export.csv

Run this BEFORE the first GitHub Action run, so existing cases keep their
existing summaries/tags rather than being re-generated by the LLM.

Expected CSV columns: CaseID, Stage, Postcode, Suburb, State, Summary, Tags,
                     Status, CaseDate, Type
"""
import csv
import sys

from . import config, reconcile, transform


def seed(csv_path: str) -> int:
    cases: dict = {}
    with open(csv_path, encoding="utf-8-sig") as f:
        reader = csv.DictReader(f)
        for row in reader:
            cid = str(row.get("CaseID") or row.get("case_id") or "").strip()
            if not cid:
                continue

            tags_raw = (row.get("Tags") or "").strip()
            tags = [t.strip() for t in tags_raw.split(",") if t.strip()]

            cases[cid] = {
                "case_id":   cid,
                "stage":     (row.get("Stage")    or "").strip(),
                "status":    (row.get("Status")   or "").strip(),
                "postcode":  (row.get("Postcode") or "").strip(),
                "suburb":    (row.get("Suburb")   or "").strip(),
                "state":     (row.get("State")    or "").strip(),
                "summary":   (row.get("Summary")  or "").strip(),
                "tags":      tags,
                "case_date": transform.normalize_date(row.get("CaseDate") or ""),
                "type":      (row.get("Type") or "Application").strip(),
            }

    reconcile.save_master(config.MASTER_PATH, cases)
    print(f"Seeded {config.MASTER_PATH} with {len(cases)} cases.")
    return 0


if __name__ == "__main__":
    if len(sys.argv) != 2:
        print("Usage: python -m scripts.seed_master <path-to-csv>")
        sys.exit(1)
    sys.exit(seed(sys.argv[1]))
